// ────────────────────────────────────────────────────────────────────────────
// __espcompose — internal compiler plumbing for reactive data binding
//
// This module is NOT part of the public API. The double-underscore prefix
// signals that it is reserved for compiler-generated code.
//
// The CLI's reactive transformer emits calls to:
//   __espcompose.compiled()     — pre-computed C++ reactive nodes
//   __espcompose.slotted()      — slot-substituted reactive nodes
//   __espcompose.derivedMemo()  — explicit C++ memo construction
// ────────────────────────────────────────────────────────────────────────────

import { IRReactiveNode } from './reactive-node';
import type { IRDependency } from './reactive-node';
import type { IRExprNode, ExprType } from './ir/expr-types';
import { registerReactiveNode } from './hooks/useReactiveScope';

// ────────────────────────────────────────────────────────────────────────────
// Library format version validation
// ────────────────────────────────────────────────────────────────────────────

/** Format versions this SDK can consume. */
export const SUPPORTED_FORMAT_VERSIONS: readonly number[] = [1];

/**
 * Validate that a compiled library's format version is supported by this SDK.
 * Throws a clear error if the version is missing or incompatible.
 *
 * Libraries stamp `__espcompose_format__` into their entry point at build time.
 * Call this at import time to catch version mismatches early.
 */
export function validateLibraryFormat(version: unknown): void {
  if (typeof version !== 'number') {
    throw new Error(
      'This ESPCompose library was not compiled with format versioning. ' +
      'Rebuild the library with the latest ESPCompose CLI (`espcompose build --library`).',
    );
  }
  if (!SUPPORTED_FORMAT_VERSIONS.includes(version)) {
    throw new Error(
      `This ESPCompose library was compiled with format v${version}, ` +
      `but this SDK supports format v${SUPPORTED_FORMAT_VERSIONS.join(', v')}. ` +
      'Please rebuild the library with a compatible ESPCompose CLI version.',
    );
  }
}

export const __espcompose = {

  /**
   * Create a IRReactiveNode from pre-computed metadata.
   *
   * This is the compile-time entry point — the CLI's reactive transformer
   * AST-compiles expressions and injects calls to this method.
   *
   * @internal — generated by the compiler, not for direct user use.
   */
  compiled<T>(meta: {
    type: ExprType;
    deps: Array<{
      sourceId: string;
      triggerType: string;
      sourceDomain: string;
      sourceType?: string;
    }>;
    expr: IRExprNode;
  }): IRReactiveNode<T> {
    const dependencies: IRDependency[] = meta.deps.map(d => ({
      kind: 'dependency' as const,
      sourceId: d.sourceId,
      triggerType: d.triggerType,
      sourceDomain: d.sourceDomain,
      sourceType: (d.sourceType as 'ha_entity' | 'theme' | undefined),
    }));

    const node = new IRReactiveNode<T>({
      kind: 'memo',
      dependencies,
      exprType: meta.type,
    });

    node.exprIR = meta.expr;

    registerReactiveNode(node);
    return node;
  },

  /**
   * Create a IRReactiveNode from a template with slot placeholders.
   *
   * The compiler emits IRExprSlot nodes for Signal<T>-typed subexpressions
   * that can't be resolved statically. At runtime this method resolves
   * the slots using the provided IRReactiveNode arguments.
   *
   * @internal — generated by the compiler, not for direct user use.
   */
  slotted<R>(
    meta: { type: ExprType; slots: number; expr: IRExprNode },
    ...signals: unknown[]
  ): IRReactiveNode<R> {
    const allDeps: IRDependency[] = [];

    for (let i = 0; i < meta.slots; i++) {
      const sig = signals[i];
      if (!sig) continue;
      // Only extract dependencies from IRReactiveNode values; skip plain primitives
      if (sig instanceof IRReactiveNode) {
        allDeps.push(...sig.dependencies);
      }
    }

    const node = __espcompose.derivedMemo<R>({
      exprType: meta.type,
      dependencies: allDeps,
      exprIR: resolveIRExprSlots(meta.expr, signals),
    });

    return node;
  },

  /**
   * Create a derived memo with an explicit ExprIR expression.
   *
   * Use this when the expression IR is already known and doesn't need
   * to go through the compiler transform (e.g. internal generated code).
   */
  derivedMemo<T>(opts: {
    exprType: ExprType;
    dependencies: IRDependency[];
    exprIR: IRExprNode;
  }): IRReactiveNode<T> {
    const node = new IRReactiveNode<T>({
      kind: 'memo',
      dependencies: opts.dependencies,
      exprType: opts.exprType,
    });
    node.exprIR = opts.exprIR;
    registerReactiveNode(node);
    return node;
  },
};

/**
 * Walk an IRExprNode tree and replace IRExprSlot nodes with resolved entity/theme
 * references from the provided signal IRReactiveNodes.
 */
function resolveIRExprSlots(expr: IRExprNode, signals: unknown[]): IRExprNode {
  if (expr.kind === 'slot') {
    const sig = signals[expr.slotIndex];
    if (sig == null) return expr;
    // Plain primitive values → literal nodes
    if (typeof sig === 'string') return { kind: 'literal', value: sig, type: 'string' };
    if (typeof sig === 'number') return { kind: 'literal', value: sig, type: 'float' };
    if (typeof sig === 'boolean') return { kind: 'literal', value: sig, type: 'bool' };
    // IRReactiveNode: use exprIR if available
    const node = sig as IRReactiveNode;
    if (node.exprIR) return node.exprIR;
    // Resolve from dependency metadata
    const dep = node.dependencies[0];
    if (dep?.sourceType === 'theme') {
      const path = dep.sourceId === '__theme__' ? dep.triggerType : '';
      // Extract scopeId from sourceId pattern __theme_<scopeId>__
      const match = dep.sourceId.match(/^__theme_([a-f0-9]+)__$/);
      const scopeId = match?.[1] ?? '';
      return { kind: 'theme_read', scope: '', scopeId, path, type: node.exprType ?? 'float' };
    }
    // Default: entity prop
    const sourceId = node.sourceId ?? dep?.sourceId ?? '';
    const property = node.property ?? 'value';
    return { kind: 'entity_prop', entityId: sourceId, property, type: node.exprType ?? 'float' };
  }

  // Recursively resolve children
  switch (expr.kind) {
    case 'binary':
      return { ...expr, left: resolveIRExprSlots(expr.left, signals), right: resolveIRExprSlots(expr.right, signals) };
    case 'unary':
    case 'postfix':
      return { ...expr, operand: resolveIRExprSlots(expr.operand, signals) };
    case 'ternary':
      return { ...expr, test: resolveIRExprSlots(expr.test, signals), consequent: resolveIRExprSlots(expr.consequent, signals), alternate: resolveIRExprSlots(expr.alternate, signals) };
    case 'call':
      return { ...expr, args: expr.args.map(a => resolveIRExprSlots(a, signals)) };
    case 'concat':
      return { ...expr, parts: expr.parts.map(p => resolveIRExprSlots(p, signals)) };
    case 'to_string':
      return { ...expr, expr: resolveIRExprSlots(expr.expr, signals) };
    case 'group':
      return { ...expr, expr: resolveIRExprSlots(expr.expr, signals) };
    case 'resolve_font':
      return { ...expr, family: resolveIRExprSlots(expr.family, signals), size: resolveIRExprSlots(expr.size, signals) };
    case 'type_cast':
      return { ...expr, expr: resolveIRExprSlots(expr.expr, signals) };
    case 'format_string':
      return { ...expr, expr: resolveIRExprSlots(expr.expr, signals) };
    case 'null_coalesce':
      return { ...expr, left: resolveIRExprSlots(expr.left, signals), right: resolveIRExprSlots(expr.right, signals) };
    case 'string_method':
      return { ...expr, object: resolveIRExprSlots(expr.object, signals), args: expr.args.map(a => resolveIRExprSlots(a, signals)) };
    case 'array_index':
      return { ...expr, array: resolveIRExprSlots(expr.array, signals), index: resolveIRExprSlots(expr.index, signals) };
    case 'array_method':
      return { ...expr, object: resolveIRExprSlots(expr.object, signals), args: expr.args.map(a => resolveIRExprSlots(a, signals)) };
    // Leaf nodes with no child expressions
    case 'literal':
    case 'signal_read':
    case 'memo_read':
    case 'theme_read':
    case 'entity_prop':
    case 'global_read':
    case 'component_read':
    case 'trigger_var':
      return expr;
    default: {
      const _exhaustive: never = expr;
      throw new Error(`resolveIRExprSlots: unhandled expression kind '${(_exhaustive as { kind: string }).kind}'`);
    }
  }
}
