import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  defaultSidebar: [
    "intro",
    "getting-started",
    {
      type: "category",
      label: "Concepts",
      items: [{ type: "autogenerated", dirName: "concepts" }],
    },
    {
      type: "category",
      label: "API Reference",
      items: [{ type: "autogenerated", dirName: "api" }],
    },
    {
      type: "category",
      label: "UI Library",
      items: [{ type: "autogenerated", dirName: "ui" }],
    },
    {
      type: "category",
      label: "Examples",
      items: [{ type: "autogenerated", dirName: "examples" }],
    },
    {
      type: "category",
      label: "Architecture",
      items: [{ type: "autogenerated", dirName: "architecture" }],
    },
  ],
};

export default sidebars;
